# Generated by Django 5.0.3 on 2024-03-18 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='title',
        ),
    ]
